### ISSUE TITLE
Cluebot NG Report interface and Wikimedia login 

### ISSUE THREAD

**Issue by IllusionFlame** [cluebotng/report#10]
I went to the Cluebot NG interface to help review false positive reports. I clicked sign in. I tried to login with my Wikimedia account, but it wouldn’t let me. It just kept refreshing the screen and asking me if I wanted to allow over and over again after I clicked allow. Does anyone else know how to fix this?

**Comment by IllusionFlame** [comment]
Can this be done?

**Comment by IllusionFlame** [comment]
Is anyone monitoring this?

**Comment by methecooldude** [comment]
> Is anyone monitoring this?

Yes, calm down...

**Comment by IllusionFlame** [comment]
> > Is anyone monitoring this?
> 
> Yes, calm down...

I am calm. I think it’s a valid question after 2 months of no reply.

**Comment by methecooldude** [comment]
RIght, I'll try and have a look... what is your Wikipedia username? Is it the same as here?

**Comment by IllusionFlame** [comment]
Yeah, it’s Illusion Flame.

**Comment by DamianZaremba** [comment]
> > > Is anyone monitoring this?
> > 
> > 
> > Yes, calm down...
> 
> I am calm. I think it’s a valid question after 2 months of no reply.

It's an open source project, feel free to send a PR... or some more detailed reproduction steps (the login is working fine for me, as it was 2 months ago).

Assuming your wikipedia login is `Illusion Flame`, you don't exist in the local users table, which implies oauth never called back to the app (creating the user).

Can you provide at least the list of urls visited while trying to authenticate.

**Comment by IllusionFlame** [comment]
I tried it again in a different web browser and it works fine. Thanks!
